[project]
name = "arc-tartiflette"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Méo Desbois-Renaudin", email = "meo-externe.desbois-renaudin@edf.fr" }
]
requires-python = ">=3.10,<3.11"
dependencies = [
    "pip-system-certs>=5.2",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "torch>=2.8.0",
    "transformers>=4.55.2",
    "trl>=0.21.0",
]

[project.scripts]
arc-tartiflette = "arc_tartiflette:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
