[project]
name = "arc_tartiflette"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Méo Desbois-Renaudin", email = "meo.desbois@gmail.com" }
]
requires-python = ">=3.10,<3.13"
dependencies = [
    "transformers",
    "bitsandbytes",
    "datasets",
    "torch>=2.4,<2.9",
    "huggingface-hub",
    "dotenv",
]

[project.scripts]
arc-tartiflette = "arc_tartiflette:main"

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[dependency-groups]
dev = [
    "trl",
    "matplotlib>=3.10.7",
    "pyqt6>=6.10.0",
    "trl",
    "peft",
]

[project.optional-dependencies]
train = [
    "peft",
    "trl",
]
