name: Build & Push to Google Artifact Registry

on:
  push:
    branches:
      - main   # Trigger only on main branch pushes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Free disk space
        run: |
          chmod a+x scripts/runner/free_disk_space.sh
          bash scripts/runner/free_disk_space.sh

      - name: Push Docker Image to Google Artifact Registry
        uses: a94763075/push-to-gar-github-action@v0.3.3
        with:
          gcloud_service_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          registry: ${{ secrets.GOOGLE_CLOUD_REGION }}-docker.pkg.dev
          repository: arc-tartiflette
          image_name: arc-app
          image_tags: 'latest,main'
          dockerfile: './Dockerfile'